use super::{SvgStyle, apply_style_overrides_to_xml};
use crate::svg_fontdb::{render_svg_to_pixmap, svg_font_db};

const LUCIDE_BELL: &[u8] = include_bytes!("../tests/fixtures/lucide-bell.svg");

#[test]
fn cached_scale_preserves_pixel_aligned_icon_edges() {
    // These edges land on whole pixels at 16px. Scale bucketing used to
    // introduce partially covered pixels along otherwise sharp edges.
    let source = br#"<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path d="M6 6h6v12H6z"/></svg>"#;
    let fonts = svg_font_db();
    for dpr in [1.0, 1.25, 1.5, 2.0, 3.0] {
        let scale = crate::svg_scale::RasterScaleKey::from_scale(16.0 / 24.0 * dpr)
            .unwrap()
            .as_f32();
        let pixmap = render_svg_to_pixmap(source, scale, &fonts, None, 4096).unwrap();
        assert!(
            pixmap
                .pixels()
                .iter()
                .all(|p| p.alpha() == 0 || p.alpha() == 255),
            "pixel-aligned edges became soft at DPR {dpr}"
        );
    }
}

fn alpha_sum(pixmap: &tiny_skia::Pixmap) -> u64 {
    pixmap
        .data()
        .chunks_exact(4)
        .map(|rgba| u64::from(rgba[3]))
        .sum()
}

#[test]
fn lucide_coverage_tracks_chromium_at_dpr_one_two_and_three() {
    // Canvas 2D reference generated by lucide-stroke-reference.html. The
    // comparison is normalized back to logical coverage so DPR only adds
    // resolution, not visual weight.
    let chromium = [
        (16.0, [12_897_u64, 14_013, 13_949]),
        (20.0, [21_475_u64, 21_299, 21_705]),
        (24.0, [30_511_u64, 31_385, 31_195]),
    ];
    let fonts = svg_font_db();

    for (size, references) in chromium {
        for (index, dpr) in [1.0_f32, 2.0, 3.0].into_iter().enumerate() {
            let scale = size / 24.0 * dpr;
            let pixmap = render_svg_to_pixmap(LUCIDE_BELL, scale, &fonts, None, 4096)
                .expect("Lucide SVG raster");
            assert_eq!(pixmap.width(), (size * dpr).round() as u32);
            assert_eq!(pixmap.height(), (size * dpr).round() as u32);
            let logical_alpha = alpha_sum(&pixmap) as f64 / f64::from(dpr * dpr);
            let ratio = logical_alpha / references[index] as f64;
            assert!(
                (0.85..=1.15).contains(&ratio),
                "{size}px at DPR {dpr} has {ratio:.3}x Chromium alpha coverage"
            );
        }
    }
}

#[test]
fn color_override_preserves_authored_stroke_geometry() {
    let source = br#"<svg stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M0 0h24"/></svg>"#;
    let styled = apply_style_overrides_to_xml(
        source,
        SvgStyle::new().with_stroke(crate::ColorLinPremul::from_srgba_u8([23, 23, 23, 255])),
    )
    .expect("style override");
    let styled = std::str::from_utf8(&styled).expect("UTF-8 SVG");
    assert!(styled.contains("stroke=\"#171717\""));
    assert!(styled.contains("stroke-width=\"2\""));
    assert!(styled.contains("stroke-linecap=\"round\""));
    assert!(styled.contains("stroke-linejoin=\"round\""));
}
